### ISSUE TITLE
Memory consumption when doing a segtrain with kraken v >=4

### ISSUE THREAD

**Issue by pkzli** [mittagessen/kraken#423] opened 2023-01-30 15:54 UTC
Hello, when I try to do a segtrain, for example :

```
ketos segtrain   -f alto transcript/document-*xml
```
It systemically ends with an error of type

```
RuntimeError: DataLoader worker (pid(s) 8260) exited unexpectedly
```

When I try to run this command on a cluster, I get an oom killer message. And when I run it locally, I observe the ketos process consuming all my ram (32GB) before being killed. It happens even with very small dataset (here it's with 20 images).

I don't observe the same behavior with `ketos train` commands.

I'm using python 3.10.6 and I attach the requirements file I'm using. Any help is welcome.

[kraken-4.2.0-p3.10.txt](https://github.com/mittagessen/kraken/files/10537404/kraken-4.2.0-p3.10.txt)

**Comment by mittagessen** [comment] 2023-02-01 23:50
Can you run the same command with some verbosity switches? Large memory consumption can be caused by your dataset being broken somehow so the worker tries to load replacement samples which in turn might also be broken causing very deep recursion and high memory use.

**Comment by pkzli** [comment] 2023-02-02 14:00
Yes it's probably something like that. I once had a python recursion error, and once the training finished correctly ... Here is the full output for a run 

```
ketos segtrain   -f alto transcript/document-*xml
Training line types:
  default	2	2548
Training region types:
  Footnote	3	30
  text	4	2
  PageNumber	5	20
  PageTitle	6	20
  Main	7	40
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
┏━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃    ┃ Name      ┃ Type                     ┃ Params ┃
┡━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0  │ net       │ MultiParamSequential     │  1.3 M │
│ 1  │ net.C_0   │ ActConv2D                │  9.5 K │
│ 2  │ net.Gn_1  │ GroupNorm                │    128 │
│ 3  │ net.C_2   │ ActConv2D                │ 73.9 K │
│ 4  │ net.Gn_3  │ GroupNorm                │    256 │
│ 5  │ net.C_4   │ ActConv2D                │  147 K │
│ 6  │ net.Gn_5  │ GroupNorm                │    256 │
│ 7  │ net.C_6   │ ActConv2D                │  295 K │
│ 8  │ net.Gn_7  │ GroupNorm                │    512 │
│ 9  │ net.C_8   │ ActConv2D                │  590 K │
│ 10 │ net.Gn_9  │ GroupNorm                │    512 │
│ 11 │ net.L_10  │ TransposedSummarizingRNN │ 74.2 K │
│ 12 │ net.L_11  │ TransposedSummarizingRNN │ 25.1 K │
│ 13 │ net.C_12  │ ActConv2D                │  2.1 K │
│ 14 │ net.Gn_13 │ GroupNorm                │     64 │
│ 15 │ net.L_14  │ TransposedSummarizingRNN │ 16.9 K │
│ 16 │ net.L_15  │ TransposedSummarizingRNN │ 25.1 K │
│ 17 │ net.l_16  │ ActConv2D                │    520 │
└────┴───────────┴──────────────────────────┴────────┘
Trainable params: 1.3 M                                                                              
Non-trainable params: 0                                                                              
Total params: 1.3 M                                                                                  
Total estimated model params size (MB): 5                                                            
Validation Sanity Check ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2 -:--:-- 0:00:26  
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/torch/utils/data/ │
│ dataloader.py:1011 in _try_get_data                                                              │
│                                                                                                  │
│   1008 │   │   # Returns a 2-tuple:                                                              │
│   1009 │   │   #   (bool: whether successfully get data, any: data if successful else None)      │
│   1010 │   │   try:                                                                              │
│ ❱ 1011 │   │   │   data = self._data_queue.get(timeout=timeout)                                  │
│   1012 │   │   │   return (True, data)                                                           │
│   1013 │   │   except Exception as e:                                                            │
│   1014 │   │   │   # At timeout and error, we manually check whether any worker has              │
│                                                                                                  │
│ /usr/lib/python3.10/queue.py:180 in get                                                          │
│                                                                                                  │
│   177 │   │   │   │   │   remaining = endtime - time()                                           │
│   178 │   │   │   │   │   if remaining <= 0.0:                                                   │
│   179 │   │   │   │   │   │   raise Empty                                                        │
│ ❱ 180 │   │   │   │   │   self.not_empty.wait(remaining)                                         │
│   181 │   │   │   item = self._get()                                                             │
│   182 │   │   │   self.not_full.notify()                                                         │
│   183 │   │   │   return item                                                                    │
│                                                                                                  │
│ /usr/lib/python3.10/threading.py:324 in wait                                                     │
│                                                                                                  │
│    321 │   │   │   │   gotit = True                                                              │
│    322 │   │   │   else:                                                                         │
│    323 │   │   │   │   if timeout > 0:                                                           │
│ ❱  324 │   │   │   │   │   gotit = waiter.acquire(True, timeout)                                 │
│    325 │   │   │   │   else:                                                                     │
│    326 │   │   │   │   │   gotit = waiter.acquire(False)                                         │
│    327 │   │   │   return gotit                                                                  │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/torch/utils/data/ │
│ _utils/signal_handling.py:66 in handler                                                          │
│                                                                                                  │
│   63 │   def handler(signum, frame):                                                             │
│   64 │   │   # This following call uses `waitid` with WNOHANG from C side. Therefore,            │
│   65 │   │   # Python can still get and update the process status successfully.                  │
│ ❱ 66 │   │   _error_if_any_worker_fails()                                                        │
│   67 │   │   if previous_handler is not None:                                                    │
│   68 │   │   │   assert callable(previous_handler)                                               │
│   69 │   │   │   previous_handler(signum, frame)                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: DataLoader worker (pid 5398) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/bin/ketos:8 in <module>                        │
│                                                                                                  │
│   5 from kraken.ketos import cli                                                                 │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:113 │
│ 0 in __call__                                                                                    │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:105 │
│ 5 in main                                                                                        │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:165 │
│ 7 in invoke                                                                                      │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:140 │
│ 4 in invoke                                                                                      │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:760 │
│ in invoke                                                                                        │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/decorators. │
│ py:26 in new_func                                                                                │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/kraken/ketos/segm │
│ entation.py:319 in segtrain                                                                      │
│                                                                                                  │
│   316 │   │   │   │   │   │   │   precision=int(precision),                                      │
│   317 │   │   │   │   │   │   │   **val_check_interval)                                          │
│   318 │                                                                                          │
│ ❱ 319 │   trainer.fit(model)                                                                     │
│   320 │                                                                                          │
│   321 │   if quit == 'early':                                                                    │
│   322 │   │   message('Moving best model {0}_{1}.mlmodel ({2}) to {0}_best.mlmodel'.format(      │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/kraken/lib/train. │
│ py:95 in fit                                                                                     │
│                                                                                                  │
│    92 │   │   with warnings.catch_warnings():                                                    │
│    93 │   │   │   warnings.filterwarnings(action='ignore', category=UserWarning,                 │
│    94 │   │   │   │   │   │   │   │   │   message='The dataloader,')                             │
│ ❱  95 │   │   │   super().fit(*args, **kwargs)                                                   │
│    96                                                                                            │
│    97                                                                                            │
│    98 class KrakenSetOneChannelMode(Callback):                                                   │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:608 in fit                                                                   │
│                                                                                                  │
│    605 │   │   if not isinstance(model, pl.LightningModule):                                     │
│    606 │   │   │   raise TypeError(f"`Trainer.fit()` requires a `LightningModule`, got: {model.  │
│    607 │   │   self.strategy._lightning_module = model                                           │
│ ❱  608 │   │   call._call_and_handle_interrupt(                                                  │
│    609 │   │   │   self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule,  │
│    610 │   │   )                                                                                 │
│    611                                                                                           │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/call.py:38 in _call_and_handle_interrupt                                                │
│                                                                                                  │
│   35 │   │   if trainer.strategy.launcher is not None:                                           │
│   36 │   │   │   return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer,     │
│   37 │   │   else:                                                                               │
│ ❱ 38 │   │   │   return trainer_fn(*args, **kwargs)                                              │
│   39 │                                                                                           │
│   40 │   except _TunerExitException:                                                             │
│   41 │   │   trainer._call_teardown_hook()                                                       │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:650 in _fit_impl                                                             │
│                                                                                                  │
│    647 │   │   │   model_provided=True,                                                          │
│    648 │   │   │   model_connected=self.lightning_module is not None,                            │
│    649 │   │   )                                                                                 │
│ ❱  650 │   │   self._run(model, ckpt_path=self.ckpt_path)                                        │
│    651 │   │                                                                                     │
│    652 │   │   assert self.state.stopped                                                         │
│    653 │   │   self.training = False                                                             │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:1103 in _run                                                                 │
│                                                                                                  │
│   1100 │   │                                                                                     │
│   1101 │   │   self._checkpoint_connector.resume_end()                                           │
│   1102 │   │                                                                                     │
│ ❱ 1103 │   │   results = self._run_stage()                                                       │
│   1104 │   │                                                                                     │
│   1105 │   │   log.detail(f"{self.__class__.__name__}: trainer tearing down")                    │
│   1106 │   │   self._teardown()                                                                  │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:1182 in _run_stage                                                           │
│                                                                                                  │
│   1179 │   │   │   return self._run_evaluate()                                                   │
│   1180 │   │   if self.predicting:                                                               │
│   1181 │   │   │   return self._run_predict()                                                    │
│ ❱ 1182 │   │   self._run_train()                                                                 │
│   1183 │                                                                                         │
│   1184 │   def _pre_training_routine(self) -> None:                                              │
│   1185 │   │   # wait for all to join if on distributed                                          │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:1195 in _run_train                                                           │
│                                                                                                  │
│   1192 │   │   self._pre_training_routine()                                                      │
│   1193 │   │                                                                                     │
│   1194 │   │   with isolate_rng():                                                               │
│ ❱ 1195 │   │   │   self._run_sanity_check()                                                      │
│   1196 │   │                                                                                     │
│   1197 │   │   # enable train mode                                                               │
│   1198 │   │   assert self.model is not None                                                     │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:1267 in _run_sanity_check                                                    │
│                                                                                                  │
│   1264 │   │   │                                                                                 │
│   1265 │   │   │   # run eval step                                                               │
│   1266 │   │   │   with torch.no_grad():                                                         │
│ ❱ 1267 │   │   │   │   val_loop.run()                                                            │
│   1268 │   │   │                                                                                 │
│   1269 │   │   │   self._call_callback_hooks("on_sanity_check_end")                              │
│   1270                                                                                           │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /loops/loop.py:199 in run                                                                        │
│                                                                                                  │
│   196 │   │   while not self.done:                                                               │
│   197 │   │   │   try:                                                                           │
│   198 │   │   │   │   self.on_advance_start(*args, **kwargs)                                     │
│ ❱ 199 │   │   │   │   self.advance(*args, **kwargs)                                              │
│   200 │   │   │   │   self.on_advance_end()                                                      │
│   201 │   │   │   │   self._restarting = False                                                   │
│   202 │   │   │   except StopIteration:                                                          │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /loops/dataloader/evaluation_loop.py:152 in advance                                              │
│                                                                                                  │
│   149 │   │   kwargs = OrderedDict()                                                             │
│   150 │   │   if self.num_dataloaders > 1:                                                       │
│   151 │   │   │   kwargs["dataloader_idx"] = dataloader_idx                                      │
│ ❱ 152 │   │   dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)       │
│   153 │   │                                                                                      │
│   154 │   │   # store batch level output per dataloader                                          │
│   155 │   │   self._outputs.append(dl_outputs)                                                   │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /loops/loop.py:199 in run                                                                        │
│                                                                                                  │
│   196 │   │   while not self.done:                                                               │
│   197 │   │   │   try:                                                                           │
│   198 │   │   │   │   self.on_advance_start(*args, **kwargs)                                     │
│ ❱ 199 │   │   │   │   self.advance(*args, **kwargs)                                              │
│   200 │   │   │   │   self.on_advance_end()                                                      │
│   201 │   │   │   │   self._restarting = False                                                   │
│   202 │   │   │   except StopIteration:                                                          │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /loops/epoch/evaluation_epoch_loop.py:121 in advance                                             │
│                                                                                                  │
│   118 │   │   """                                                                                │
│   119 │   │   if not isinstance(data_fetcher, DataLoaderIterDataFetcher):                        │
│   120 │   │   │   batch_idx = self.batch_progress.current.ready                                  │
│ ❱ 121 │   │   │   batch = next(data_fetcher)                                                     │
│   122 │   │   else:                                                                              │
│   123 │   │   │   batch_idx, batch = next(data_fetcher)                                          │
│   124 │   │   self.batch_progress.is_last_batch = data_fetcher.done                              │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /utilities/fetching.py:184 in __next__                                                           │
│                                                                                                  │
│   181 │   │   return self                                                                        │
│   182 │                                                                                          │
│   183 │   def __next__(self) -> Any:                                                             │
│ ❱ 184 │   │   return self.fetching_function()                                                    │
│   185 │                                                                                          │
│   186 │   def reset(self) -> None:                                                               │
│   187 │   │   self.fetched = 0                                                                   │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /utilities/fetching.py:265 in fetching_function                                                  │
│                                                                                                  │
│   262 │   │   elif not self.done:                                                                │
│   263 │   │   │   # this will run only when no pre-fetching was done.                            │
│   264 │   │   │   try:                                                                           │
│ ❱ 265 │   │   │   │   self._fetch_next_batch(self.dataloader_iter)                               │
│   266 │   │   │   │   # consume the batch we just fetched                                        │
│   267 │   │   │   │   batch = self.batches.pop(0)                                                │
│   268 │   │   │   except StopIteration as e:                                                     │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /utilities/fetching.py:280 in _fetch_next_batch                                                  │
│                                                                                                  │
│   277 │   def _fetch_next_batch(self, iterator: Iterator) -> None:                               │
│   278 │   │   start_output = self.on_fetch_start()                                               │
│   279 │   │   try:                                                                               │
│ ❱ 280 │   │   │   batch = next(iterator)                                                         │
│   281 │   │   except StopIteration as e:                                                         │
│   282 │   │   │   self._stop_profiler()                                                          │
│   283 │   │   │   raise e                                                                        │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/torch/utils/data/ │
│ dataloader.py:530 in __next__                                                                    │
│                                                                                                  │
│    527 │   │   with torch.autograd.profiler.record_function(self._profile_name):                 │
│    528 │   │   │   if self._sampler_iter is None:                                                │
│    529 │   │   │   │   self._reset()                                                             │
│ ❱  530 │   │   │   data = self._next_data()                                                      │
│    531 │   │   │   self._num_yielded += 1                                                        │
│    532 │   │   │   if self._dataset_kind == _DatasetKind.Iterable and \                          │
│    533 │   │   │   │   │   self._IterableDataset_len_called is not None and \                    │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/torch/utils/data/ │
│ dataloader.py:1207 in _next_data                                                                 │
│                                                                                                  │
│   1204 │   │   │   │   return self._process_data(data)                                           │
│   1205 │   │   │                                                                                 │
│   1206 │   │   │   assert not self._shutdown and self._tasks_outstanding > 0                     │
│ ❱ 1207 │   │   │   idx, data = self._get_data()                                                  │
│   1208 │   │   │   self._tasks_outstanding -= 1                                                  │
│   1209 │   │   │   if self._dataset_kind == _DatasetKind.Iterable:                               │
│   1210 │   │   │   │   # Check for _IterableDatasetStopIteration                                 │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/torch/utils/data/ │
│ dataloader.py:1163 in _get_data                                                                  │
│                                                                                                  │
│   1160 │   │   │   │   raise RuntimeError('DataLoader timed out after {} seconds'.format(self._  │
│   1161 │   │   elif self._pin_memory:                                                            │
│   1162 │   │   │   while self._pin_memory_thread.is_alive():                                     │
│ ❱ 1163 │   │   │   │   success, data = self._try_get_data()                                      │
│   1164 │   │   │   │   if success:                                                               │
│   1165 │   │   │   │   │   return data                                                           │
│   1166 │   │   │   else:                                                                         │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/torch/utils/data/ │
│ dataloader.py:1024 in _try_get_data                                                              │
│                                                                                                  │
│   1021 │   │   │   │   │   self._mark_worker_as_unavailable(worker_id)                           │
│   1022 │   │   │   if len(failed_workers) > 0:                                                   │
│   1023 │   │   │   │   pids_str = ', '.join(str(w.pid) for w in failed_workers)                  │
│ ❱ 1024 │   │   │   │   raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.f  │
│   1025 │   │   │   if isinstance(e, queue.Empty):                                                │
│   1026 │   │   │   │   return (False, None)                                                      │
│   1027 │   │   │   import tempfile                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: DataLoader worker (pid(s) 5398) exited unexpectedly
```

Then how to "unbroke" my dataset ? Or make sure that it is in a correct state ? And could the behavior be non-deterministic ? Because I think I was able to run the command once on this same dataset.

**Comment by mittagessen** [comment] 2023-02-02 14:31
Can you run:

```
ketos -vvv segtrain -f alto transcript/document-*.xml
```

? If there's a problem with the data you'll see messages like:

```
Failed. Replacing with sample $number
```

**Comment by pkzli** [comment] 2023-02-02 14:56
This time I get this, a problem with Python version ?

```
ketos -vvv  segtrain  -f alto transcript/document-*.xml | grep nl
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/bin/ketos:8 in <module>                        │
│                                                                                                  │
│   5 from kraken.ketos import cli                                                                 │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:113 │
│ 0 in __call__                                                                                    │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:105 │
│ 5 in main                                                                                        │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:165 │
│ 7 in invoke                                                                                      │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:140 │
│ 4 in invoke                                                                                      │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/core.py:760 │
│ in invoke                                                                                        │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/click/decorators. │
│ py:26 in new_func                                                                                │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/kraken/ketos/segm │
│ entation.py:319 in segtrain                                                                      │
│                                                                                                  │
│   316 │   │   │   │   │   │   │   precision=int(precision),                                      │
│   317 │   │   │   │   │   │   │   **val_check_interval)                                          │
│   318 │                                                                                          │
│ ❱ 319 │   trainer.fit(model)                                                                     │
│   320 │                                                                                          │
│   321 │   if quit == 'early':                                                                    │
│   322 │   │   message('Moving best model {0}_{1}.mlmodel ({2}) to {0}_best.mlmodel'.format(      │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/kraken/lib/train. │
│ py:95 in fit                                                                                     │
│                                                                                                  │
│    92 │   │   with warnings.catch_warnings():                                                    │
│    93 │   │   │   warnings.filterwarnings(action='ignore', category=UserWarning,                 │
│    94 │   │   │   │   │   │   │   │   │   message='The dataloader,')                             │
│ ❱  95 │   │   │   super().fit(*args, **kwargs)                                                   │
│    96                                                                                            │
│    97                                                                                            │
│    98 class KrakenSetOneChannelMode(Callback):                                                   │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:608 in fit                                                                   │
│                                                                                                  │
│    605 │   │   if not isinstance(model, pl.LightningModule):                                     │
│    606 │   │   │   raise TypeError(f"`Trainer.fit()` requires a `LightningModule`, got: {model.  │
│    607 │   │   self.strategy._lightning_module = model                                           │
│ ❱  608 │   │   call._call_and_handle_interrupt(                                                  │
│    609 │   │   │   self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule,  │
│    610 │   │   )                                                                                 │
│    611                                                                                           │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/call.py:38 in _call_and_handle_interrupt                                                │
│                                                                                                  │
│   35 │   │   if trainer.strategy.launcher is not None:                                           │
│   36 │   │   │   return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer,     │
│   37 │   │   else:                                                                               │
│ ❱ 38 │   │   │   return trainer_fn(*args, **kwargs)                                              │
│   39 │                                                                                           │
│   40 │   except _TunerExitException:                                                             │
│   41 │   │   trainer._call_teardown_hook()                                                       │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:650 in _fit_impl                                                             │
│                                                                                                  │
│    647 │   │   │   model_provided=True,                                                          │
│    648 │   │   │   model_connected=self.lightning_module is not None,                            │
│    649 │   │   )                                                                                 │
│ ❱  650 │   │   self._run(model, ckpt_path=self.ckpt_path)                                        │
│    651 │   │                                                                                     │
│    652 │   │   assert self.state.stopped                                                         │
│    653 │   │   self.training = False                                                             │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:1042 in _run                                                                 │
│                                                                                                  │
│   1039 │   │   self.strategy.setup_environment()                                                 │
│   1040 │   │   self.__setup_profiler()                                                           │
│   1041 │   │                                                                                     │
│ ❱ 1042 │   │   self._call_setup_hook()  # allow user to setup lightning_module in accelerator e  │
│   1043 │   │                                                                                     │
│   1044 │   │   # check if we should delay restoring checkpoint till later                        │
│   1045 │   │   if not self.strategy.restore_checkpoint_after_setup:                              │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:1291 in _call_setup_hook                                                     │
│                                                                                                  │
│   1288 │   │   if self.datamodule is not None:                                                   │
│   1289 │   │   │   self._call_lightning_datamodule_hook("setup", stage=fn)                       │
│   1290 │   │   self._call_callback_hooks("setup", stage=fn)                                      │
│ ❱ 1291 │   │   self._call_lightning_module_hook("setup", stage=fn)                               │
│   1292 │   │                                                                                     │
│   1293 │   │   self.strategy.barrier("post_setup")                                               │
│   1294                                                                                           │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/pytorch_lightning │
│ /trainer/trainer.py:1347 in _call_lightning_module_hook                                          │
│                                                                                                  │
│   1344 │   │   pl_module._current_fx_name = hook_name                                            │
│   1345 │   │                                                                                     │
│   1346 │   │   with self.profiler.profile(f"[LightningModule]{pl_module.__class__.__name__}.{ho  │
│ ❱ 1347 │   │   │   output = fn(*args, **kwargs)                                                  │
│   1348 │   │                                                                                     │
│   1349 │   │   # restore current_fx when nested context                                          │
│   1350 │   │   pl_module._current_fx_name = prev_fx_name                                         │
│                                                                                                  │
│ /home/pierre/kraken-env/kraken-4.2.0-p3.10.in-env/lib/python3.10/site-packages/kraken/lib/train. │
│ py:773 in setup                                                                                  │
│                                                                                                  │
│   770 │   │   if stage in [None, 'fit']:                                                         │
│   771 │   │   │   if not self.model:                                                             │
│   772 │   │   │   │   self.spec = f'[{self.spec[1:-1]} O2l{self.train_set.dataset.num_classes}   │
│ ❱ 773 │   │   │   │   logger.info(f'Creating model {self.spec} with {self.train_set.dataset.nu   │
│   774 │   │   │   │   nn = vgsl.TorchVGSLModel(self.spec)                                        │
│   775 │   │   │   │   if self.bounding_regions is not None:                                      │
│   776 │   │   │   │   │   nn.user_metadata['bounding_regions'] = self.bounding_regions           │
│                                                                                                  │
│ /usr/lib/python3.10/logging/__init__.py:1477 in info                                             │
│                                                                                                  │
│   1474 │   │   logger.info("Houston, we have a %s", "interesting problem", exc_info=1)           │
│   1475 │   │   """                                                                               │
│   1476 │   │   if self.isEnabledFor(INFO):                                                       │
│ ❱ 1477 │   │   │   self._log(INFO, msg, args, **kwargs)                                          │
│   1478 │                                                                                         │
│   1479 │   def warning(self, msg, *args, **kwargs):                                              │
│   1480 │   │   """                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Logger._log() got an unexpected keyword argument 'nl'
```

**Comment by mittagessen** [comment] 2023-02-02 18:10
On 23/02/02 06:56AM, Pierre Kunzli wrote:
> This time I get this, a problem with Python version ?

Ahh no, it's a bug in the version of kraken you're running. It has been
fixed in master for a while though.

**Comment by pkzli** [comment] 2023-02-04 11:53
Just tried with commit 911fcac6d5c02a34fcafa413becb327f889c16bf , seems to solve the problem. Would you recommend working with master branch ?

**Comment by mittagessen** [comment] 2023-02-04 14:04
Interesting. I haven't really touched the dataloader code much. You can work with master for now but I'm currently stabilizing it for a new release so it is possible that not every commit will work. There will be a new stable release soon, once I got all the bugs I'm aware of ironed out.

**Closed by mittagessen** 2023-02-04 14:04 UTC
