### ISSUE TITLE
Problems in pageseg.py

### ISSUE THREAD

**Issue by whatda** [mittagessen/kraken#11] opened 2015-10-17 15:23 UTC
Hi,

I wanted to test your tool so I installed it on my Ubuntu machine and tried to run it, but I got the following error:

    File "/usr/local/lib/python2.7/dist-packages/kraken/pageseg.py", line 250, in compute_line_seeds
        bmarked *= (bottom > threshold*np.amax(bottom)*threshold)*(1-colseps)
    TypeError: Cannot cast ufunc multiply output from dtype('int32') to dtype('bool') with casting rule     'same_kind'

Although I don't know Python, I found a stackoverflow answer suggesting to add braces and `.astype()`. I found that two rows seem to be affected and after replacing them, kraken works for me. The new rows look as follows:

`bmarked *= ((bottom > threshold*np.amax(bottom)*threshold)*(1-colseps)).astype(bmarked.dtype)`

and

`tmarked *= ((top > threshold*np.amax(top)*threshold/2)*(1-colseps)).astype(bmarked.dtype)`

**Comment by mittagessen** [comment] 2015-10-17 21:10
Thanks for the report, the segmentation code is taken directly from ocropus and hasn't been touched in quite a while (so this issue was probably introduced when numpy changed their in-place casting behavior).

Could you attach one of your input files? It's possible there are similar errors caused by in-place assignment in other places and I'd like to fix all I can find before closing this issue.

**Comment by whatda** [comment] 2015-10-18 02:06
NP. This should be reproducible with any input, for example this image: https://upload.wikimedia.org/wikipedia/commons/7/75/Dan'l_Druce,_Blacksmith_-_Illustrated_London_News,_November_18,_1876_-_text.png

Funny though, I just tried ocropy and had a similar error. Since I haven't touched it for several months, I guess it has to do with updated Python stuff.

**Comment by QuLogic** [comment] 2015-10-18 03:43
[Recent builds](https://travis-ci.org/mittagessen/kraken/jobs/85988518) are also failing for probably the same reason.

**Comment by mittagessen** [comment] 2015-10-18 12:33
Yeah it is caused by the numpy people changing behavior of type-casting between 1.9.x and 1.10 (it's even in their future changes section of the changelog). Should be fixed in 0.7.2.

**Closed by mittagessen** 2015-10-18 12:33 UTC
