### ISSUE TITLE
RuntimeError: set_num_threads expects a positive integer (training on CPU)

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [mittagessen/kraken#161] opened 2019-11-13 10:34 UTC
While trying to train on CPU, I obtain the following error: RuntimeError: set_num_threads expects a positive integer. If I launch,
```
 ketos train book/*.png
```

```
Initializing model ✓
Traceback (most recent call last):
  File "/home/jbc//kraken/env/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/kraken/ketos.py", line 351, in train
    nn.set_num_threads(threads)
  File "/home/jbc//kraken/env/lib/python3.6/site-packages/kraken/lib/vgsl.py", line 193, in set_num_threads
    torch.set_num_threads(num)
RuntimeError: set_num_threads expects a positive integer
```

The error remains if I specify the number of threads with
```
ketos train --threads 4 book/*.png
```

**Comment by mittagessen** [comment] 2019-11-13 10:47
* Jean-Baptiste-Camps :: 2019-11-13 11:34 Wed:
> While trying to train on CPU, I obtain the following error: RuntimeError: set_num_threads expects a positive integer. If I launch,
> ```
>  ketos train book/*.png
> ```

I assume you're using the blla or an older stable release? This should
have been fixed in master (and setting it to something > 2 should be a
sufficient workaround). Make sure that you have commit
e27bccce2163ebd8d34e279aa99947ee6a48f25e, release 2.0.6 or newer.

The behavior of the openmp thread setting has changed recently in
pytorch and it now throws an error instead of silently ignoring
non-positive numbers (of course they didn't document that).

**Comment by Jean-Baptiste-Camps** [comment] 2019-11-13 10:53
Thanks for the information. I'm using pip for installing, and so have version 2.0.5. I'll try updating !

**Comment by mittagessen** [comment] 2019-11-13 11:06
* Jean-Baptiste-Camps :: 2019-11-13 11:53 Wed:
> Thanks for the information. I'm using pip for installing, and so have version 2.0.5. I'll try updating !

OK, then the CI auto-deploy broke again. God, I wish it wouldn't require
constant handholding.

**Comment by Jean-Baptiste-Camps** [comment] 2019-12-09 14:36
Thanks @mittagessen , I've seen that the PyPi version has been upgraded and fixed this issue. I was about to close this, but I see that a problem, that seem to be about Torch dependencies, remain, namely `torch_shm_manager: error while loading shared libraries: libnvToolsExt.so.1: cannot open shared object file: No such file or directory`. (I'm trying to train on CPU here). The full log:

```
torch_shm_manager: error while loading shared libraries: libnvToolsExt.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/kraken/ketos.py", line 401, in train
    trainer.run(_print_eval, _draw_progressbar)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/kraken/lib/train.py", line 263, in run
    for _, (input, target) in zip(range(self.event_it), self.train_set):
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "/home/jbc/Data/Cours/Cours-ENC-2019-20/Cours/Philologie_computationnelle_M2HN/1_01_paleogr/kraken/env/lib/python3.6/site-packages/torch/bin/torch_shm_manager" at /pytorch/torch/lib/libshm/core.cpp:99

torch_shm_manager: error while loading shared libraries: libnvToolsExt.so.1: cannot open shared object file: No such file or directory
```

**Comment by mittagessen** [comment] 2019-12-09 14:55
* Jean-Baptiste-Camps :: 2019-12-09 15:36 Mon:
> Thanks @mittagessen , I've seen that the PyPi version has been
> upgraded and fixed this issue. I was about to close this, but I see
> that a problem, that seem to be about Torch dependencies, remain,
> namely `torch_shm_manager: error while loading shared libraries:
> libnvToolsExt.so.1: cannot open shared object file: No such file or
> directory`. (I'm trying to train on CPU here). The full log:

This is a bit weird because the latest pypi package works on multiple
system I've tried it on. Do you have a partial CUDA installation on your
system? Could you try running this simple example in a python shell in
the virtual env and tell me if you get the same error:

```
import torch
torch.randn(1, 4, 234)
```

?

**Comment by Jean-Baptiste-Camps** [comment] 2019-12-09 15:29
Normally, I should have no CUDA installation at all. Weird.

This works:

```
tensor([[[-1.3239e+00, -1.6219e-01,  9.9282e-01,  6.8563e-01,  1.1869e+00,
          -3.3249e-01, -1.8236e-01,  1.7806e+00, -7.8711e-01,  7.3522e-01,
           1.4296e+00, -1.0234e-01, -1.2698e+00, -2.8765e-01,  1.0543e+00,
           9.3623e-01,  1.1211e+00, -1.3868e-01,  6.4508e-01,  1.2209e+00,
          -4.7047e-01,  4.1543e-01,  1.7511e+00,  6.9431e-01, -2.6950e-02,
           6.3409e-01, -9.4866e-01,  1.1785e-01,  3.6643e-02,  1.3804e-01,
           2.9352e-01,  9.0862e-01, -1.4881e+00,  1.0507e-01, -8.6659e-01,
          -7.7873e-01,  8.1988e-01,  1.8043e+00, -1.9385e+00,  1.6997e-01,
          -1.0081e+00,  2.6169e-01, -6.9317e-01,  7.1124e-01, -3.1454e-01,
           2.2850e+00,  1.0487e+00,  9.8144e-01,  5.0895e-01,  1.1232e+00,
          -3.7608e-02, -1.2283e+00,  1.9861e-01, -7.0302e-01, -2.1147e-01,
           3.5137e-03, -7.9581e-01, -4.6714e-01, -2.7339e+00,  1.0349e+00,
           1.7155e+00,  7.0560e-01,  1.0525e+00, -2.6242e+00, -3.8226e-01,
          -4.0820e-01,  1.7314e+00,  1.0311e+00,  8.3619e-01,  1.7142e+00,
           6.8757e-01,  3.9593e-01,  6.1888e-01, -3.5639e-01, -4.8030e-02,
           1.3104e+00,  7.8828e-02,  2.6526e-01, -9.8729e-01, -1.4499e+00,
           9.8668e-01, -1.4707e+00,  4.8579e-01, -1.8382e+00,  1.4378e+00,
           1.0865e+00, -1.2432e+00, -4.1860e-01,  3.3173e-01,  1.0212e+00,
           1.8517e+00, -9.0589e-02,  2.6788e-01,  4.3420e-01,  4.2777e-01,
           9.7435e-01,  1.4814e+00,  3.5799e-01, -1.4310e+00,  1.0119e+00,
          -2.1572e-01, -1.0372e+00, -4.9430e-01,  7.8418e-01, -8.6627e-01,
          -4.9288e-01, -5.1533e-01, -7.1477e-01,  7.0487e-01, -5.5380e-01,
          -1.2137e-01,  1.8122e-01,  8.5561e-01,  3.6750e-01, -5.8344e-01,
           2.9192e+00, -9.0285e-01, -1.0881e+00,  1.2447e+00,  6.8080e-01,
           6.0266e-01,  1.1627e+00, -4.9763e-01,  1.6527e+00, -1.6606e+00,
           7.9125e-01, -4.4591e-02, -5.6461e-02, -5.6611e-01, -7.6523e-01,
          -6.9446e-01,  7.5607e-02,  4.2664e-01,  1.1815e+00,  8.2842e-01,
           2.8324e-01,  8.3072e-01, -6.2881e-01,  1.2461e+00, -1.2320e+00,
           1.0774e+00,  8.8527e-01,  2.8463e-01,  2.8855e-01, -3.0519e-01,
          -5.0560e-01, -5.1703e-01, -9.1706e-01,  1.1453e+00, -1.4676e+00,
          -6.7653e-01,  1.8157e-01, -3.1004e-01, -8.4645e-01,  1.2655e-01,
          -1.8409e+00, -2.8766e-02,  4.6455e-01, -1.9235e-01, -1.1231e+00,
          -4.5350e-01, -4.0364e-01,  3.6372e-01,  9.6916e-01, -1.9417e-01,
          -1.7349e+00, -1.2712e+00, -4.8377e-01, -1.1750e+00,  4.6944e-01,
           3.8858e-02, -1.1704e+00, -5.4475e-01,  8.7916e-01, -1.2288e+00,
           4.9404e-01, -5.3211e-01,  3.7720e-01, -5.6737e-01,  2.9313e-01,
           3.3645e-01, -1.3500e-01, -1.3018e+00,  1.2216e+00,  1.0501e+00,
          -1.0889e-01, -5.5390e-02,  7.4818e-01,  1.8631e+00, -1.1247e+00,
          -5.9722e-01, -1.4557e+00,  9.5837e-01, -2.2178e+00, -1.5608e-01,
           3.6695e-01, -1.0147e-02,  3.0894e-01, -9.1178e-01, -9.1325e-01,
           1.0194e+00, -1.1406e+00,  1.7605e+00, -1.4349e+00,  8.3974e-01,
           7.5957e-01, -6.5927e-01, -1.2040e+00,  4.7885e-01, -8.9007e-01,
          -1.3404e+00,  1.3123e+00, -1.4629e+00,  1.3554e-01,  7.9602e-02,
           1.0600e+00, -4.2843e-01,  9.2467e-01, -1.9131e-01,  1.2392e+00,
           3.9862e-01,  7.3072e-01,  1.1080e+00,  7.2964e-01,  8.2599e-01,
          -5.3192e-03,  1.9999e-01, -7.5641e-01, -1.0903e+00,  2.7407e-01,
           2.5919e+00,  1.2155e+00, -7.9568e-01, -9.0862e-01],
         [-6.0373e-02, -9.0306e-01,  8.4326e-01, -1.0462e+00,  8.2873e-01,
           1.0579e+00, -2.2868e+00,  1.8269e+00, -1.1869e+00, -8.9832e-01,
           5.7826e-01,  1.6125e+00, -7.8516e-01, -1.9850e-01,  7.4085e-01,
           4.1051e-01,  4.0583e-01, -2.1962e-02,  4.3973e-01, -9.5519e-01,
          -1.0385e+00,  3.1055e-01,  4.3348e-01,  1.6393e-01, -4.3320e-01,
           8.8893e-02, -7.7849e-01,  8.4679e-01, -7.2957e-01,  6.5168e-01,
           1.1551e-01,  4.9899e-01,  1.5264e+00, -9.2717e-01,  8.9072e-01,
           1.0763e+00,  7.9738e-02, -1.9876e-01, -1.6565e+00,  3.2187e+00,
           1.1533e+00, -4.8203e-01,  8.2575e-01,  7.3266e-01, -6.9020e-01,
           9.3801e-02,  1.8925e+00,  6.4955e-01,  5.7307e-02,  2.0558e+00,
          -4.2299e-03,  1.6351e+00,  9.0841e-01, -6.9061e-01,  9.2280e-02,
           9.9429e-01, -2.9170e-01,  7.7505e-01, -3.8222e-01,  1.1939e+00,
          -1.3030e+00,  1.5628e+00, -2.2089e-01, -7.2123e-01,  6.9757e-01,
          -4.2522e-01,  8.6887e-01, -9.0623e-01,  1.0936e+00,  4.9052e-01,
          -1.3508e-01, -7.8130e-01,  5.3741e-01,  1.6880e-01, -1.7819e+00,
          -2.4293e-02, -3.4182e-01,  5.9533e-01, -1.8286e+00,  1.4311e-01,
          -1.0744e+00,  4.7968e-02,  1.5204e+00,  7.1251e-01, -4.4992e-01,
           1.0313e+00, -1.2174e+00,  2.1343e+00, -9.3998e-01, -9.6421e-02,
           6.6676e-03,  2.1405e-01, -1.4103e+00, -6.9174e-02, -6.7268e-01,
          -1.2086e+00,  2.7404e-01, -6.1783e-01, -1.3980e+00,  9.2998e-01,
           1.6731e+00,  9.2960e-01,  6.4493e-01, -4.2175e-01, -2.8724e-01,
          -3.7100e-01,  8.9083e-01, -2.0084e-01,  9.3226e-01,  4.7071e-02,
           7.3638e-01,  7.6822e-01, -9.4879e-01, -2.7042e+00,  4.5455e-01,
           8.0915e-01, -1.6410e-01,  1.3918e+00, -1.2469e+00,  7.1986e-01,
          -1.5088e+00, -1.7828e+00, -6.2519e-01, -1.0200e+00, -4.4271e-01,
          -1.4847e+00, -1.0725e-01, -1.1008e+00, -9.7968e-02,  9.3146e-01,
          -4.1957e-01,  1.1364e+00, -1.2112e-01,  1.7828e-01, -1.0150e+00,
          -1.0667e-01, -7.7692e-01,  6.4309e-02, -8.1651e-01,  5.3257e-02,
          -1.2147e+00,  1.1845e-01, -7.3846e-01, -2.1362e+00, -1.9071e+00,
          -1.8903e+00, -2.0410e-01,  1.2198e+00, -1.2974e+00,  8.0276e-02,
          -4.5394e-01, -3.4051e-01, -1.4228e+00, -5.5711e-01, -2.0494e+00,
           1.3359e+00, -2.7264e-01,  3.0205e-01, -8.3309e-01, -4.6193e-01,
           2.8650e-01,  7.1261e-01, -8.1949e-01, -2.6128e-01, -4.7935e-02,
          -1.3658e+00,  9.3708e-01, -8.5101e-01, -1.6603e-01,  1.9131e-01,
           2.9808e-01,  1.4366e+00,  3.7275e-01,  1.1646e+00,  1.1223e+00,
           9.8907e-01,  2.2842e-01,  1.2584e+00,  4.6300e-01,  6.5134e-01,
           1.0263e-01, -1.6994e-01, -1.3249e+00, -7.6015e-02, -1.6215e+00,
          -1.0532e+00,  6.5641e-01,  3.9896e-01, -1.5226e+00, -2.0916e-01,
          -1.8555e-02, -4.4899e-01,  1.7702e-01, -1.5396e+00,  5.3666e-02,
          -1.0278e+00,  1.4552e+00, -5.4280e-01, -1.5368e+00, -1.0010e-01,
           6.9234e-01,  2.8571e-01, -1.1671e+00,  1.0341e+00, -7.6580e-01,
           5.7347e-01,  2.5638e-01, -3.5886e-01, -2.8916e-01, -8.2685e-01,
          -1.5609e+00, -1.1840e+00,  1.2045e-01, -2.4970e-01, -2.2796e-01,
           2.3278e-01, -1.6148e+00, -4.4302e-01, -1.7205e+00, -1.7108e+00,
           5.2481e-01,  9.2073e-01,  3.3622e-01,  2.0620e+00,  8.1524e-01,
           7.4561e-02,  2.6148e-01,  1.8239e+00,  3.4705e-03, -2.7790e-01,
           1.2374e+00, -6.7437e-01, -1.1683e+00,  6.5611e-01],
         [ 5.4323e-01,  2.4643e+00,  2.0175e+00, -2.6385e-01, -4.5686e-01,
          -1.1976e+00,  2.2985e+00,  4.8872e-01, -1.5788e+00,  6.6020e-01,
          -1.4010e+00, -3.4894e-01,  1.1742e+00,  1.2484e+00, -1.0050e+00,
          -3.6899e-02,  8.3349e-01, -6.2409e-01,  1.0381e+00, -7.7012e-01,
          -9.4843e-01,  3.2298e-01,  4.9877e-01, -1.0549e+00,  3.5517e-01,
          -1.9819e+00, -2.0734e+00, -6.6521e-01, -3.5596e-02, -3.0919e-01,
           5.3533e-01, -2.7452e+00, -1.2046e+00, -1.0289e+00, -1.4848e+00,
           2.1757e+00,  4.6248e-01, -1.6242e-01,  7.0060e-01, -1.4374e+00,
          -6.9829e-01, -4.0885e-01, -4.0914e-01, -4.3572e-01,  3.1282e-01,
           1.1500e+00,  1.6101e+00, -1.2170e+00, -9.7138e-01,  6.3654e-03,
          -1.1872e+00,  1.1233e+00,  2.7890e-01, -1.1676e+00, -7.6517e-01,
          -4.4352e-01,  3.3467e-01,  1.2426e-01, -2.1218e-01, -1.4023e+00,
          -4.2732e-01,  5.3381e-01, -7.2735e-01,  1.1311e-01,  1.2500e+00,
           4.6858e-02, -1.2257e+00,  1.1931e-01,  2.2066e+00,  8.2521e-01,
          -5.8732e-02,  7.2936e-01,  3.7612e-01, -5.2056e-01,  7.4464e-01,
          -8.5150e-01, -1.7442e-01,  4.8430e-01, -1.2797e+00, -1.7816e+00,
          -6.4973e-01,  5.8232e-01,  2.3630e+00,  8.8752e-01, -5.1680e-01,
           1.9989e-01, -1.1120e+00,  1.0126e+00,  2.2564e+00,  1.4258e+00,
           6.6542e-02, -5.2706e-01,  9.2809e-01, -1.4161e+00, -2.1741e-01,
          -1.5953e+00, -1.2360e-01,  1.1029e+00,  7.7022e-01, -1.1142e-01,
          -8.3615e-01, -3.5816e-01, -2.7328e+00,  1.3723e+00,  9.5150e-01,
           3.4601e-01,  5.7045e-01, -1.1390e+00, -3.4542e-01, -5.7920e-01,
           4.2594e-02, -1.3809e+00,  5.6185e-01,  9.8137e-01, -1.9205e+00,
           3.5079e+00,  1.1274e+00, -9.4387e-01, -3.1356e-01,  3.3892e-01,
           2.4134e-01, -4.1010e-01, -1.4871e+00, -1.8450e-01, -1.0743e+00,
           3.8620e-01,  8.7610e-01,  1.0738e+00,  2.3742e-02, -1.5264e+00,
          -9.4510e-01, -2.3634e-01,  5.8749e-01,  1.2126e+00,  2.4501e+00,
          -1.7759e-01,  1.1751e+00, -9.1021e-01,  1.5637e+00,  1.2319e+00,
           9.2583e-01,  6.1044e-02, -2.4761e-01,  1.7973e+00,  2.1311e+00,
           1.0943e-01,  5.1331e-02,  3.6512e-01,  1.0979e+00, -2.2051e-01,
           9.3982e-01,  1.0048e+00, -2.6796e-01,  1.0235e-02,  1.3616e+00,
           1.2939e+00,  2.3283e+00, -1.9938e-01, -3.0454e-01, -1.2609e+00,
          -1.5408e-02, -6.5158e-01,  6.5207e-02, -1.2535e+00, -6.5006e-01,
           1.8882e-01, -7.4145e-01, -9.8699e-01, -7.1563e-02,  4.0981e-02,
           3.1283e-01, -6.0452e-01,  1.3325e+00, -1.7433e-02, -8.0837e-01,
          -2.7505e-01,  1.0654e+00,  2.6405e-01, -3.1623e-01,  1.1407e-01,
           6.7187e-01,  6.8024e-01,  1.0347e+00,  5.2920e-01, -1.0496e-01,
          -2.0983e-01, -2.1692e+00,  2.6789e-01,  7.1003e-01,  1.6773e+00,
          -6.6333e-01,  2.7899e-01, -1.3682e+00, -2.1604e+00,  1.2091e+00,
          -4.5720e-01,  4.5704e-01, -1.1307e-01,  7.2771e-01, -1.3478e+00,
           1.0244e+00,  9.2179e-02, -1.8103e+00,  5.2908e-01,  7.9693e-01,
          -1.3870e+00, -1.6971e+00,  4.4246e-01, -1.2827e+00,  1.5011e-01,
           8.4252e-02, -9.5695e-01, -9.4732e-01,  1.5909e+00,  5.8625e-03,
           1.2738e+00, -4.1710e-02,  8.5486e-01, -1.1770e-02,  1.1205e+00,
           2.2909e-01,  1.4193e+00,  6.2727e-01,  1.3396e+00,  5.5467e-01,
           7.8736e-01, -9.0884e-01,  1.0213e+00,  8.1283e-01,  4.7604e-01,
           9.0687e-01,  3.1843e+00, -5.8978e-01, -1.0559e+00],
         [-5.8436e-01, -7.3148e-01, -3.3456e-01,  9.2962e-03,  2.2553e-01,
           4.7405e-01,  1.7677e+00,  2.8360e-01, -2.6398e+00,  4.0136e-01,
           2.2729e-01, -4.7542e-01,  1.1969e+00, -1.0795e+00, -2.1453e-01,
          -1.1604e+00, -1.8537e-01, -9.6715e-01, -4.0867e-01, -8.3971e-01,
          -3.2482e-01, -3.3147e-01, -1.3306e+00,  9.3572e-01,  1.7884e+00,
          -1.1127e+00,  3.0397e-01,  1.0800e+00,  8.2613e-01, -1.0781e+00,
          -4.6973e-01,  4.5288e-01,  3.8739e-01,  5.1045e-01, -6.6435e-02,
          -5.7765e-01,  1.3294e+00,  5.3699e-01, -1.8243e-01,  2.9264e-01,
          -3.3238e-01,  1.2576e-01, -7.4841e-01,  1.4309e+00,  8.1430e-01,
          -7.1386e-01,  2.9418e-01, -1.5525e+00,  2.0700e-01,  5.7040e-01,
           2.0597e+00, -4.7959e-03, -4.7452e-01,  1.7491e-01, -1.0537e+00,
           7.9255e-01, -1.0206e+00, -2.2433e-02,  1.6361e+00,  2.0072e+00,
           1.3384e+00, -6.2474e-01, -2.9592e-01, -6.1139e-01, -6.8528e-02,
          -1.1973e+00,  1.9555e-01,  2.3300e-01,  3.0247e+00,  1.6437e-01,
           5.6353e-01,  9.8930e-01,  8.8960e-01,  1.3120e+00,  1.0038e+00,
           1.5965e+00, -7.6458e-01,  1.1276e-01, -1.0762e+00,  2.2467e+00,
           1.2328e+00,  5.7336e-01,  1.0023e+00,  8.5433e-01,  1.8542e+00,
           6.9008e-01, -1.9361e+00, -1.0976e-01, -1.4803e-01, -1.2992e+00,
           2.2429e-01,  4.7626e-01,  5.0560e-01, -6.8344e-01, -1.0612e+00,
           1.3621e+00, -9.9668e-01,  7.9301e-01, -6.7271e-01,  1.7329e-01,
           2.7129e-01,  5.2916e-01, -1.6297e+00, -7.9157e-01,  8.7887e-02,
          -1.4597e+00, -1.1069e+00,  8.4844e-01, -2.0329e+00,  8.9566e-01,
          -1.5197e+00,  8.8523e-01,  3.0261e-01, -5.6323e-01, -3.7531e-01,
          -3.3012e-01,  1.5934e+00, -8.7923e-01,  1.2668e-02,  1.3255e+00,
           2.1369e-01,  1.4772e+00, -3.7395e-01,  9.6272e-01, -2.9256e-02,
          -1.4246e+00, -6.6118e-02, -9.2243e-01, -3.0805e-03,  9.2995e-01,
          -4.9407e-01, -1.1836e+00,  2.7192e+00,  1.7231e-01, -1.2666e+00,
          -2.1173e+00, -1.7237e-01, -4.7422e-01,  4.0158e-01, -2.4083e+00,
           1.3073e-01,  8.7937e-01,  6.7343e-02, -5.7450e-01,  3.5477e-01,
          -1.7491e-01, -1.7010e-01, -1.2717e+00, -4.4663e-01, -6.5574e-01,
           1.3916e+00,  3.8417e-01, -4.3409e-01,  3.9615e-01, -5.4821e-01,
          -4.7414e-01,  1.9267e-01,  1.2694e+00, -1.4437e+00,  2.8183e-01,
           5.0364e-01, -2.1178e+00,  1.4849e+00, -6.9848e-01,  2.9914e-01,
           2.6987e-01, -4.4789e-01,  5.9933e-01, -1.0598e+00, -6.2113e-01,
           5.2631e-02, -7.7518e-01,  5.8236e-01,  6.8328e-02,  5.6443e-01,
          -7.8447e-01, -8.9189e-01,  8.4039e-02, -1.1944e-01,  6.0220e-01,
          -5.8628e-01, -4.8281e-02, -2.3964e+00,  2.1127e-01,  1.9538e+00,
           1.3780e+00,  3.4478e-01, -1.4148e+00, -7.2943e-02, -3.0538e-01,
          -6.4677e-01, -1.0024e-01, -4.2465e-01,  3.2870e-01,  3.3462e-01,
           3.8524e-01,  3.5219e-01,  8.1159e-01, -6.8540e-01, -1.7058e+00,
           1.1272e+00, -4.4602e-01,  8.7650e-01,  1.6886e+00, -1.0585e+00,
          -7.1238e-01,  7.0993e-01, -9.9052e-01, -1.3920e+00, -2.4588e+00,
           4.3308e-01,  5.0660e-01, -7.7149e-01, -9.5658e-01,  1.2156e-01,
           1.0249e+00,  6.2085e-01, -7.6167e-01, -1.7985e+00, -6.3696e-01,
          -5.9614e-01, -1.0271e+00, -3.3350e-01,  4.6513e-01,  1.3500e+00,
          -2.4976e-02,  1.3126e+00, -1.4210e+00, -1.2706e+00,  9.5813e-01,
          -1.2632e-01, -5.9454e-01, -4.3073e-01,  1.0744e+00]]])
```

**Comment by mrocr** [comment] 2019-12-23 14:31
I think i faced something like this before, in my situation, it was caused by a bug in Pytorch.
Usually, when you want to use CPU only, pytorch sets the device to `-1`. The issue is, some versions of pytorch don't accept negative device.
Perhaps an addition of `map_location='cpu')` would do the trick.

@Jean-Baptiste-Camps post your system specs+os so that I can create for you a custom `environment.yml` to install using conda. Also, which branch of kraken you want, master?

**Closed** 2020-04-03 01:04 UTC
