### ISSUE TITLE
Kraken cracks when using a clstm module with 800 hidden

### ISSUE THREAD

**Issue by christophered** [mittagessen/kraken#53] opened 2017-07-12 23:13 UTC
Peace be upon you
I have trained 2 clstm modules, the first using nhidden=100, and the second using nhidden=800.
The purpose was to see if there was any improvement in the recognition.
[I have used the clstm of the separate-derivs to train those modules.](https://github.com/tmbdev/clstm/tree/separate-derivs)

Later on, I used the first module in Kraken which successfully recognized the text perfectly.
But when using the second clstm module that I created using nhidden=800, Kraken cracks down in error in the ocr step.
It seems that if i use any module created with anything more than nhidden=100, kraken can't handle.

[The nhidden=100 module](https://github.com/mittagessen/kraken/files/1143579/arabic-9000-100.zip)
[The nhidden=800 module](https://github.com/mittagessen/kraken/files/1143580/arabic-9000-800.zip)
[The training data](https://github.com/mittagessen/kraken/files/1143582/training.data.zip)

Here is the error when using the nhidden=800 module:
```
bmwmy@ubuntu:~/Desktop/test$ kraken -i 000001.png out.txt binarize segment ocr -m arabic-9000-800.clstm
Loading RNN	✓
Binarizing	✓
Segmenting	✓
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 142, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 101, in recognizer
    for pred in it:
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 222, in rpred
    yield bidi_record(ocr_record(pred, pos, conf))
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 98, in bidi_record
    for i, j in enumerate(record):
  File "/usr/local/lib/python2.7/dist-packages/future/types/newobject.py", line 71, in next
    return type(self).__next__(self)
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 56, in __next__
    return (self.prediction[self.idx], self.cuts[self.idx],
IndexError: list index out of range

**Comment by andbue** [comment] 2017-07-17 10:37
Hi there,
I could replicate the bug - even on my pytorch based fork of kraken, so the problem is not the clstm code. The reason for the error seems to be that somehow translate_back and translate_back_locations in some cases can have different output length. As a workaround I stopped using the output of translate_back in rpred and used translate_back_locations for prediction and locations.
This is just my idea, I haven't tested it in detail and I don't know how much of is applicable to the official clstm based kraken.

**Comment by christophered** [comment] 2017-07-17 11:38
@andbue can you test the recognition rate of nhidden=100 vs 800
@mittagessen what do you think?

**Comment by andbue** [comment] 2017-07-17 11:56
I didn't do any testing of the recognition rate, but the 800 doesn't output anything at all. I'm relatively new to this, but I guess that you need more training iterations for larger hidden layers?

**Comment by christophered** [comment] 2017-07-17 12:16
@andbue when you train an clstm model via clstmocrtrain, it shows you the error rate and progress of the model. You can train your own model for perhaps 9000 rounds or until it reaches 0.xx error rate.
If you need guidance I can help you. The aim is to see the if training hidden 800 achieves significant results vs 100.

**Comment by mittagessen** [comment] 2017-07-17 12:58
I've been looking into it and the issue seems to be translate_back_locations, indeed. The error could be fixed by just switching to translate_back_locations completely and I'll do that as soon as possible without breaking any old functionality.

How stable is pytorch? Does it still use pickle for serialization? I really want to switch to a maintained library but that is still an absolute no-go.

**Comment by amitdo** [comment] 2017-07-17 13:03
Here is @andbue's fork:
https://github.com/andbue/kraken

**Comment by mittagessen** [comment] 2017-07-17 13:23
So the latest commit should fix differing output lengths for predictString and translate_back_locations, although the difference obviously persists for pyrnn models.
The failing decoder is weird because the output of the network is sufficiently above the default threshold (plenty of 1.0 outputs) but I'll look into it.

**Closed** 2017-07-17 13:57 UTC

**Comment by andbue** [comment] 2017-07-17 14:23
@christophered I'm not able to make any comparison at the moment using clstm (because on my debian system a recent update broke some required library).  I'm currently testing different sizes on your training data using my torch based fork. To make testing work, I had to disable code point reordering. I'll report later how different model size affects performance.

@mittagessen Pytorch ist still work in progress, there is some weird behaviour every now and then, e.g. max() delivers wrong output when on gpu. A problem is the ctc-alignment: there is warp-ctc, but the pytorch bindings (https://github.com/SeanNaren/warp-ctc/tree/pytorch_bindings/pytorch_binding) are not in the official repositories yet.
The serialization is normally done in pickle, but I wrote some import and export functions to make it work using the clstm protobuf format (https://github.com/andbue/kraken/blob/master/kraken/lib/tlstm.py). At some point in the clstm development they decided to change the size of the weights, so I implemented two modes, "clstm" and "clstm_legacy", to support models built using the old separate_derivs branch of clstm.
The good thing about the torch stuff is that it runs on cuda out of the box. With my cheap geforce gtx 1050 ti (more did not fit into my university office pc) I can run 1000 iterations of training in less than 5 mins. It might be possible to increase performance even more by writing a gt_set that's held in gpu memory or by using other kinds of optimizers - pytorch has lots of functions to play around with.

**Comment by mittagessen** [comment] 2017-07-17 14:45
There is a slight difference between clstm protobuf files where the content of the `name` and `kind` attributes changed slightly but the weights are exactly the same and are interoperable.

Building a general protobuf that is able to serialize arbitrary network configurations would be desirable but would require heavier involvement with pytorch (or any other ML library) development than I can handle right now. 

The training rate is almost certainly limited by the SGD as each sample has to be loaded separately. Doing mini-batches will speed up training considerably. Just feeding 100 samples at once and doing the back-propagation should make everything a lot faster.

**Comment by andbue** [comment] 2017-07-17 15:16
The weight of the linear layer - in clstm it's called the softmax weight - is of size noutput x (2*nhidden + 1) when trained with the clstm master branch and of size noutput x 2*nhidden when trained with the separate-derivs branch. To make it compatible, I concatenate the weight with a vector of zeros. If you want to upgrade to the master branch of clstm at some point, it will be no problem to convert your models.

@christophered I trained two models using ketos, the first with nhidden=100, the second with nhidden=800. Unfortunately, the larger model is more than 10 times slower, so I aborted training after 2000 iterations. Here are the results:

nhidden = 100:
[time] -------------------- iteration - % acc. - chars in testset - errors
[103.7150] Accuracy report (1000) 0.2114 563 444
[186.9544] Accuracy report (2000) 0.8490 563 85
[269.4989] Accuracy report (3000) 0.8845 563 65
[353.4791] Accuracy report (4000) 0.9307 563 39
[434.3994] Accuracy report (5000) 0.9396 563 34
[518.1553] Accuracy report (6000) 0.9218 563 44
[602.4578] Accuracy report (7000) 0.9627 563 21
[684.8107] Accuracy report (8000) 0.9467 563 30
[768.7921] Accuracy report (9000) 0.9343 563 37
[849.3088] Accuracy report (10000) 0.9414 563 33
[934.0800] Accuracy report (11000) 0.9218 563 44

nhidden = 800:
[1151.9115] Accuracy report (1000) 0.8495 372 56
[2255.4735] Accuracy report (2000) 0.9489 372 19

**Comment by amitdo** [comment] 2017-07-17 16:02
>can run 1000 iterations of training in less than 5 mins.

How much less?
You should compare it to clstm with cpu (1 core, 1 thread used).
Note that clstm does line normalization for each line in every iteration.

https://github.com/tmbdev/clstm/issues/70

**Comment by mittagessen** [comment] 2017-07-17 18:08
The gt_set class preprocesses all line image and keeps them in memory (@andbue's fork uses my half-finished training stuff). In fact the line normalization is considerably slower than the actual forward-backward passes so quite a bit of the performance improvement probably comes from that (IIRC training single-core with caching is already considerably <10min/1000 iterations) and the real improvement will come from doing batching instead of pure SGD.
